### ISSUE TITLE
failed to enroll - unable to decode input

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-android#187]
An unexpired token can not be decoded to enroll because the base64 decoding has the wrong number of array elements?

> Caused by: java.lang.ArrayIndexOutOfBoundsException: length=256; index=65533

```
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti: failed to enroll
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti: io.jsonwebtoken.io.DecodingException: Unable to decode input: length=256; index=65533
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at io.jsonwebtoken.io.ExceptionPropagatingDecoder.decode(ExceptionPropagatingDecoder.java:41)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:288)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at io.jsonwebtoken.impl.ImmutableJwtParser.parse(ImmutableJwtParser.java:148)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at org.openziti.identity.ZitiJWT$Companion.fromJWT(ZitiJWT.kt:59)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at org.openziti.identity.Enroller$Companion$fromJWT$1.invokeSuspend(Enroller.kt:59)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=256; index=65533
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at io.jsonwebtoken.io.Base64.decodeFast(Base64.java:248)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at io.jsonwebtoken.io.Base64Decoder.decode(Base64Decoder.java:36)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at io.jsonwebtoken.io.Base64Decoder.decode(Base64Decoder.java:23)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    at io.jsonwebtoken.io.ExceptionPropagatingDecoder.decode(ExceptionPropagatingDecoder.java:36)
05-14 15:08:20.867 17092 14074 E o.o.a.Ziti:    ... 12 more
```

**Comment by ekoby** [comment]
fixed in #199
