### ISSUE TITLE
No longer working on Android TV (0.12.1)

### ISSUE THREAD

**Issue by kuhlmannmarkus** [openziti/ziti-tunnel-android#240]
Hi everyone,

I have set up ZET on my Android TV some time ago. I think it was version 0.8.0 (just after the APK got attached to the releases) and it worked just fine. Today I tried updating to 0.12.1 and found that it does no longer function. The app just closes after successful enrollment and cannot be opened again.
I'm happy to support on this issue by submitting logs, if you can tell me what you would need.

Best regards

**Comment by ekoby** [comment]
can you collect `logcat` logs for it?

**Comment by kuhlmannmarkus** [comment]
@ekoby Im not an expert on collecting logs for Android apps, but I tried my best. On a fresh installation of the tunneler app, I can select a JWT file and enrollment is succesful. Directly after the enrollment toast, the app crashes.

These are the logs I have collected by: "logcat | grep org.openziti.mobile" Please let me know if there is a way to improve log collection here.

`12-09 17:55:24.159   840  2129 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.openziti.mobile/.ZitiMobileEdgeActivity} from uid 10140
12-09 17:55:24.159  1489 17139 D ApplicationSwitchService: ** Activity starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.openziti.mobile/.ZitiMobileEdgeActivity } : org.openziti.mobile
12-09 17:55:24.159  1489  2811 D ApplicationSwitchService: AppSwitchAOSP: org.openziti.mobile / org.openziti.mobile.ZitiMobileEdgeActivity
12-09 17:55:24.168  2443  3161 D TvPowerManagerService: onApplicationSwitch entry with: org.openziti.mobile
12-09 17:55:24.168  2443  3161 D TvPowerManagerService: setAppSwitchName: org.openziti.mobile
12-09 17:55:24.168  2443  3161 D TvPowerManagerService: onApplicationSwitch exit with: org.openziti.mobile
12-09 17:55:24.169  7177  7214 D GameSwitchService:  Not a Game from APP: org.openziti.mobile
12-09 17:55:24.177  1489 17139 D ApplicationSwitchService: ** Activity resuming: org.openziti.mobile
12-09 17:55:24.192   840   870 I ActivityManager: Start proc 8388:org.openziti.mobile/u0a155 for pre-top-activity {org.openziti.mobile/org.openziti.mobile.ZitiMobileEdgeActivity}
12-09 17:55:24.379  8388  8388 W KeyStore:      at org.openziti.mobile.TunnelModel.<init>(TunnelModel.kt:188)
12-09 17:55:24.379  8388  8388 W KeyStore:      at org.openziti.mobile.ZitiMobileEdgeApp.onCreate(ZitiMobileEdgeApp.kt:35)
12-09 17:55:24.381  8388  8388 W KeyStore:      at org.openziti.mobile.TunnelModel.<init>(TunnelModel.kt:188)
12-09 17:55:24.381  8388  8388 W KeyStore:      at org.openziti.mobile.ZitiMobileEdgeApp.onCreate(ZitiMobileEdgeApp.kt:35)
12-09 17:55:24.702  8444  8444 F DEBUG   : pid: 8388, tid: 8417, name: native-tunnel  >>> org.openziti.mobile <<<
12-09 17:55:24.747  8444  8444 F DEBUG   :       #00 pc 001d20ae  /data/app/~~8F9ZD9UF-0rdIFWc6X02wg==/org.openziti.mobile-L9RuuimTPmXsRJ7yL561kQ==/base.apk!libtunnel.so (offset 0x133c000) (parse_hdrs+36) (BuildId: 6db4207aa759847c9bfb6baf413502e9066a14d1)
12-09 17:55:24.747  8444  8444 F DEBUG   :       #01 pc 001cffb3  /data/app/~~8F9ZD9UF-0rdIFWc6X02wg==/org.openziti.mobile-L9RuuimTPmXsRJ7yL561kQ==/base.apk!libtunnel.so (offset 0x133c000) (BuildId: 6db4207aa759847c9bfb6baf413502e9066a14d1)
12-09 17:55:24.747  8444  8444 F DEBUG   :       #02 pc 001dc411  /data/app/~~8F9ZD9UF-0rdIFWc6X02wg==/org.openziti.mobile-L9RuuimTPmXsRJ7yL561kQ==/base.apk!libtunnel.so (offset 0x133c000) (BuildId: 6db4207aa759847c9bfb6baf413502e9066a14d1)
12-09 17:55:24.747  8444  8444 F DEBUG   :       #03 pc 001ffed3  /data/app/~~8F9ZD9UF-0rdIFWc6X02wg==/org.openziti.mobile-L9RuuimTPmXsRJ7yL561kQ==/base.apk!libtunnel.so (offset 0x133c000) (BuildId: 6db4207aa759847c9bfb6baf413502e9066a14d1)
12-09 17:55:24.747  8444  8444 F DEBUG   :       #04 pc 001f8045  /data/app/~~8F9ZD9UF-0rdIFWc6X02wg==/org.openziti.mobile-L9RuuimTPmXsRJ7yL561kQ==/base.apk!libtunnel.so (offset 0x133c000) (uv_run+154) (BuildId: 6db4207aa759847c9bfb6baf413502e9066a14d1)
12-09 17:55:24.747  8444  8444 F DEBUG   :       #05 pc 00197c13  /data/app/~~8F9ZD9UF-0rdIFWc6X02wg==/org.openziti.mobile-L9RuuimTPmXsRJ7yL561kQ==/base.apk!libtunnel.so (offset 0x133c000) (BuildId: 6db4207aa759847c9bfb6baf413502e9066a14d1)
12-09 17:55:24.747  8444  8444 F DEBUG   :       #06 pc 0002b5e3  /data/app/~~8F9ZD9UF-0rdIFWc6X02wg==/org.openziti.mobile-L9RuuimTPmXsRJ7yL561kQ==/oat/arm/base.odex (art_jni_trampoline+74)
12-09 17:55:24.861   840   868 D ArtManagerInternalImpl: /data/misc/iorapd/org.openziti.mobile/174/org.openziti.mobile.ZitiMobileEdgeActivity/compiled_traces/compiled_trace.pb doesn't exist
12-09 17:55:24.862   840   868 I ActivityTaskManager: Displayed org.openziti.mobile/.ZitiMobileEdgeActivity: +673ms
12-09 17:55:24.903  8388  8388 I TetheringManager: registerTetheringEventCallback:org.openziti.mobile
12-09 17:55:24.948 19059 19059 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1982 onStartInput(EditorInfo{EditorInfo{packageName=org.openziti.mobile, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=0, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=2131296291, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
12-09 17:55:25.014  1489 17139 D ApplicationSwitchService: MonitorProcessController TopPackage:org.openziti.mobile
12-09 17:55:25.254  1489 17139 D ApplicationSwitchService: processName: org.openziti.mobile
12-09 17:55:25.255   840  8462 W ActivityTaskManager:   Force finishing activity org.openziti.mobile/.ZitiMobileEdgeActivity
12-09 17:55:25.257   397   530 V debugdump: Renaming msg tombstone from tombstone_02 to tombstone_02#8388#org.openziti.mobile#8417#native-tunnel#SIGNAL-7
12-09 17:55:25.257   397   530 V debugdump: Renamed tombstone file : tombstone_02#8388#org.openziti.mobile#8417#native-tunnel#SIGNAL-7
12-09 17:55:25.358   397   524 V debugdump: server: msg recevied : tombstone_02#8388#org.openziti.mobile#8417#native-tunnel#SIGNAL-7 65
12-09 17:55:25.358   397   524 V debugdump: parseMsg: pid = 8388, type = 3, maintype =java , subtype = native_crash, processname = org.openziti.mobile effect = visible
12-09 17:55:25.376   397   524 I debugdump: Generate  dumpId: dump_00000226_00000001_00976394.093391_8388, Crashed ProcessName=org.openziti.mobile
12-09 17:55:25.445   840  2671 I ActivityManager: Process org.openziti.mobile (pid 8388) has died: fg  SVC
12-09 17:55:25.447   840  2111 I WindowManager: WIN DEATH: Window{5b0c12d u0 org.openziti.mobile/org.openziti.mobile.ZitiMobileEdgeActivity}
12-09 17:55:25.447   840  2111 W InputDispatcher: Attempted to unregister already unregistered input channel '5b0c12d org.openziti.mobile/org.openziti.mobile.ZitiMobileEdgeActivity (server)'
12-09 17:55:25.488   840   868 W UsageStatsService: java.lang.IllegalArgumentException: Unable to stop usage for org.openziti.mobile, not in use
12-09 17:55:27.774  2608  2735 D candeebug: Gateway Returning successfully for event: {"event-type":"unknown.210","boot-count":226,"standby-count":1,"kernel-time":976396489,"data":{"original-event-type":210,"dumpver":2,"version":"TPM211EA_R.101.001.004.252","dumpid":"dump_00000226_00000001_00976364.892976_8080","boot-cycle":226,"standby-cycle":1,"kernel-time":976364864,"system-time":"2024-12-09 17:54:56.000+0100","pid":8080,"tid":8106,"type":"java","subtype":"native_crash","effect":"visible","process-name":"org.openziti.mobile","thread-name":"native-tunnel","oob-url":"file:\/\/\/data\/debugdump\/dump_00000226_00000001_00976364.892976_8080.zip","tssinceboot":976396486,"ver":1},"oob-url":"file:\/\/\/data\/debugdump\/dump_00000226_00000001_00976364.892976_8080.zip"}
12-09 17:55:27.777  2608  2735 D candeebug: Gateway Returning successfully for event: {"event-type":"unknown.210","boot-count":226,"standby-count":1,"kernel-time":976396492,"data":{"original-event-type":210,"dumpver":2,"version":"TPM211EA_R.101.001.004.252","dumpid":"dump_00000226_00000001_00976394.093391_8388","boot-cycle":226,"standby-cycle":1,"kernel-time":976394944,"system-time":"2024-12-09 17:55:25.000+0100","pid":8388,"tid":8417,"type":"java","subtype":"native_crash","effect":"visible","process-name":"org.openziti.mobile","thread-name":"native-tunnel","oob-url":"file:\/\/\/data\/debugdump\/dump_00000226_00000001_00976394.093391_8388.zip","tssinceboot":976396489,"ver":1},"oob-url":"file:\/\/\/data\/debugdump\/dump_00000226_00000001_00976394.093391_8388.zip"}
12-09 17:55:29.022  2608  8169 D candeebug: Gateway Returning successfully for event: {"event-type":"usage.app","boot-count":226,"standby-count":1,"kernel-time":976397738,"data":{"package_name":"org.openziti.mobile","class_name":"org.openziti.mobile.ZitiMobileEdgeActivity","timestamp":1733763295558,"action_type":1,"query_start":1733763267112,"query_end":1733763329016,"ver":1,"package_version":"v0.12.2"}}
12-09 17:55:29.028  2608  8169 D candeebug: Gateway Returning successfully for event: {"event-type":"usage.app","boot-count":226,"standby-count":1,"kernel-time":976397743,"data":{"package_name":"org.openziti.mobile","class_name":"org.openziti.mobile.ZitiMobileEdgeActivity","timestamp":1733763324827,"action_type":1,"query_start":1733763267112,"query_end":1733763329016,"ver":1,"package_version":"v0.12.2"}}
12-09 17:55:29.028  2608  8169 D candeebug: Gateway Returning successfully for event: {"event-type":"usage.app","boot-count":226,"standby-count":1,"kernel-time":976397744,"data":{"package_name":"org.openziti.mobile","class_name":"org.openziti.mobile.ZitiMobileEdgeActivity","timestamp":1733763325905,"action_type":2,"query_start":1733763267112,"query_end":1733763329016,"ver":1,"package_version":"v0.12.2"}}`

**Comment by ekoby** [comment]
thank you providing the log. it gave me some idea on what's happening.

do you mind trying the build from here: https://github.com/openziti/ziti-tunnel-android/actions/runs/12278970062 and see it fixes the issue?

**Comment by kuhlmannmarkus** [comment]
Hi @ekoby, thank you so much for taking the time!
I installed the new version and now the enrollment is no longer working: I get "java.lang.exeption: ziti controller is not available" as toast.

These are the corresponding logs:

`12-11 17:09:34.975  3453  4056 I ImageStickingService:  List = org.openziti.mobile.ZitiMobileEdgeActivity
12-11 17:09:35.799  1473  2747 D ApplicationSwitchService: Top packageName:org.openziti.mobile
12-11 17:09:38.804  1473  2747 D ApplicationSwitchService: Top packageName:org.openziti.mobile
12-11 17:09:39.691   840 10860 I ActivityTaskManager: START u0 {cmp=org.openziti.mobile/.ZitiEnrollmentActivity} from uid 10157
12-11 17:09:39.691  1473  1514 D ApplicationSwitchService: ** Activity starting: Intent { cmp=org.openziti.mobile/.ZitiEnrollmentActivity } : org.openziti.mobile
12-11 17:09:39.767   840   867 I ActivityTaskManager: Displayed org.openziti.mobile/.ZitiEnrollmentActivity: +75ms
12-11 17:09:39.779  1907  1907 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1982 onStartInput(EditorInfo{EditorInfo{packageName=org.openziti.mobile, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=0, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=-1, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
12-11 17:09:40.195   368  1634 E BufferQueueProducer: [org.openziti.mobile/org.openziti.mobile.ZitiMobileEdgeActivity#0](id:17000000046,api:0,p:-1,c:368) disconnect: not connected (req=1)
12-11 17:09:41.381   368  1634 E BufferQueueProducer: [org.openziti.mobile/org.openziti.mobile.ZitiEnrollmentActivity#0](id:17000000048,api:0,p:-1,c:368) disconnect: not connected (req=1)
12-11 17:09:45.517  1473  1514 D ApplicationSwitchService: ** Activity resuming: org.openziti.mobile
12-11 17:09:45.517  1473  2747 D ApplicationSwitchService: AppSwitchAOSP: org.openziti.mobile / class unknown
12-11 17:09:45.529  2113  2978 D CIService: onApplicationSwitch entry with: org.openziti.mobile
12-11 17:09:45.529  2113  2978 D CIApplication: setAppSwitchName: org.openziti.mobile
12-11 17:09:45.529  2113  2978 D CIService: onApplicationSwitch exit with: org.openziti.mobile
12-11 17:09:45.530  2750  7377 I NetTVShowToUService: focused app name :org.openziti.mobile
12-11 17:09:45.530  2784  3148 D TvPowerManagerService: onApplicationSwitch entry with: org.openziti.mobile
12-11 17:09:45.531  2784  3148 D TvPowerManagerService: setAppSwitchName: org.openziti.mobile
12-11 17:09:45.531  2784  3148 D TvPowerManagerService: onApplicationSwitch exit with: org.openziti.mobile
12-11 17:09:45.547  1473  1514 D ApplicationSwitchService: ** Activity resuming: org.openziti.mobile
12-11 17:09:45.577  1473  1514 D ApplicationSwitchService: MonitorProcessController TopPackage:org.openziti.mobile
12-11 17:09:45.587  1473  1514 D ApplicationSwitchService: ** Activity resuming: org.openziti.mobile
12-11 17:09:45.666  1907  1907 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1982 onStartInput(EditorInfo{EditorInfo{packageName=org.openziti.mobile, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=0, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=-1, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
12-11 17:09:46.077   368   773 E BufferQueueProducer: [org.openziti.mobile/org.openziti.mobile.ZitiEnrollmentActivity#0](id:17000000048,api:0,p:-1,c:368) disconnect: not connected (req=1)
12-11 17:09:47.810  1473  2747 D ApplicationSwitchService: Top packageName:org.openziti.mobile
12-11 17:09:50.814  1473  2747 D ApplicationSwitchService: Top packageName:org.openziti.mobile`

**Comment by ekoby** [comment]
are you trying to add a new identity?

**Comment by kuhlmannmarkus** [comment]
Yes, I installed from scratch.

**Comment by ekoby** [comment]
Did you generate another JWT? Enrollment JWTs are single use tokens

**Comment by kuhlmannmarkus** [comment]
Yes, I have created a fresh JWT. It really seems that in this version, the app can somehow not connect to the controller. 
I just tried with 0.12.3 and there the enrollment is working. I still see the app crashing right after the enrollment though.

**Comment by ekoby** [comment]
@kuhlmannmarkus sorry for a dely (holidays and such)
v0.13.0 is out now, please try that

can you send me feedback report?
Open the App -> Feedback

you can DM me on our [discourse](https://openziti.discourse.group/)

**Comment by andreabat1991** [comment]
Hi, I have the same issue with a Firestick 4k. The enrolling of the jwt is ok but when I tap on connect the app crashes. I'm on v0.13.5.

**Comment by Bosoffsky** [comment]
Hi, just testet on Google TV 12 Kernel Version 5.4.283 and Ziti Mobile Edge version 0.15 and I have the same issues mentioned above. The App has a API connection to the edge controller but cant establish a connection to the router. The app crashes seconds after starting.
